query GetFlacTracks {
    tracks(
        filters: { filename: { ends_with: ".flac" } }
        pagination: { cursor: { limit: 100 } }
    ) @paginate(mode: SinglePage) {
        # nodes contains the actual track data
        nodes {
            filePath
            # filename
            title
            artist
            album
            date
            trackNumber
            durationSecs
            # artistIds
            # workIds
            recordingId
            id
        }
        # pageInfo tells you if there are more tracks
        pageInfo {
            hasNextPage
            endCursor
        }
    }
}
